name: Scrape

on:
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      POSTGRES_URI: ${{ secrets.POSTGRES_URI }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHANNEL: ${{ secrets.TELEGRAM_CHANNEL }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go build ./cmd/itbooks

      - name: Scrape
        run: ./itbooks scrape
